trigger:
- main
pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds
variables:
  imageName: 'davidshi/metrics-server'
  dockerHub: 'dockerHub'
  tag: 'v0.5.0'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: $(tag)
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: $(tag)
    
