trigger:
- main
pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds
variables:
  imageName: 'davidshi/kube-state-metrics'
  dockerHub: 'dockerHub'
  tag: 'v2.0.0'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: $(tag)
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: $(tag)
    
