trigger:
- main
pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds
variables:
  imageName: 'metrics-server'
  dockerHub: 'dockerHub'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      v0.5.0
